_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.12.8
        t:
            "1":
                - 5
                - 6
                - 53
                - 55
            "2":
                - 5
                - 6
                - 53
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.8
            "5": 0.19.4
            "8":
                - 3
                - 5
            "12": 0.19.4
            "13": windows-amd64
gamma:
    value: 0
learning_rate:
    value: 1
max_depth:
    value: 10
min_child_weight:
    value: 1
n_estimators:
    value: 100
reg_alpha:
    value: 0.01
reg_lambda:
    value: 1
